### ISSUE TITLE
Strange behaviour on deamon mode

### ISSUE THREAD

**Issue by luftmensch-luftmensch** [protesilaos/beframe#3] opened 2024-05-06 15:32 UTC
Hi Prot,

I've encountered a strange behavior of the windows when using emacs in daemon mode.

For some reason when launching emacs the value of `frame-title-format` is not displayed as I've configured it (`'("%b – Emacs")`), but instead it shows only the the first buffer on which the first frame of emacs is opened (\*scratch\*) and it's not updating when changing buffers.

This behavior does not appear on normal instance of emacs.

Below I have attached some example (notice the bar showing the name)

## Emacsclient frame
![emacsclient frame](https://github.com/protesilaos/beframe/assets/65391343/363bb741-3ab0-42b9-917e-22f9e5530ca0)

## Emacs instance
![emacs instance](https://github.com/protesilaos/beframe/assets/65391343/780074e6-05c3-47d0-ba40-00d39051c53d)

Thanks!

**Comment by protesilaos** [comment] 2024-05-06 17:19
Hello there!

> I've encountered a strange behavior of the windows when using emacs in daemon mode.
>
> For some reason when launching emacs the value of `frame-title-format` is not displayed as I've configured it (`'("%b – Emacs")`), but instead it shows only the the first buffer on which the first frame of emacs is opened (\*scratch\*) and it's not updating when changing buffers.
>
> This behavior does not appear on normal instance of emacs.

Perhaps we need to modify the function `beframe-infer-frame-name` so that it does not set a name if there is no frame available. Maybe this:

```diff
 beframe.el | 15 ++++++++-------
 1 file changed, 8 insertions(+), 7 deletions(-)

diff --git a/beframe.el b/beframe.el
index d33f844..f1c5ebc 100644
--- a/beframe.el
+++ b/beframe.el
@@ -618,13 +618,14 @@ (defvar project--list) ; from project.el
 (defun beframe-infer-frame-name (frame name)
   "Infer a suitable name for FRAME with given NAME.
 See `beframe-rename-frame'."
-  (let* ((buffer (car (frame-parameter frame 'buffer-list)))
-         (file-name (when (bufferp buffer) (buffer-file-name buffer)))
-         (buf-name (buffer-name buffer))
-         (dir (with-current-buffer buffer (or (vc-root-dir) default-directory)))
-         (projectp (and (bound-and-true-p project--list)
-                        (listp project--list)
-                        (member (list dir) project--list))))
+  (when-let (((frame-list))
+             (buffer (car (frame-parameter frame 'buffer-list)))
+             (file-name (when (bufferp buffer) (buffer-file-name buffer)))
+             (buf-name (buffer-name buffer))
+             (dir (with-current-buffer buffer (or (vc-root-dir) default-directory)))
+             (projectp (and (bound-and-true-p project--list)
+                            (listp project--list)
+                            (member (list dir) project--list))))
     (cond
      ((and name (stringp name))
       name)
```

**Comment by luftmensch-luftmensch** [comment] 2024-05-06 19:27
Thanks a lot Prot!

With this change I got the expected behavior.

Are you going to merge this changes upstream at some point?

**Comment by protesilaos** [comment] 2024-05-07 06:29
Just merged! Thank you!

**Closed as completed by protesilaos** 2024-05-07 06:29 UTC

**Comment by luftmensch-luftmensch** [comment] 2024-08-19 21:12
Hi Prot,

Sorry to reopen the issue but I've encountered a strange behavior of the windows when using emacs in daemon mode on the latest version of `beframe`

**Comment by protesilaos** [comment] 2024-08-20 06:18
> From: Valentino ***@***.***>
> Date: Mon, 19 Aug 2024 14:12:21 -0700
>
> Hi Prot,

Hello there!

> Sorry to reopen the issue

No problem!

> but I've encountered a strange behavior of the windows when using
> emacs in daemon mode on the latest version of `beframe`

Can you tell me what the issue is? Hopefully we can fix it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by luftmensch-luftmensch** [comment] 2024-08-20 07:20
For some reason when launching emacs the value of frame-title-format is not displayed as I've configured it ('("%b – Emacs")), but instead it shows only the the first buffer on which the first frame of emacs is opened (*scratch*) and it's not updating when changing buffers.

**Comment by luftmensch-luftmensch** [comment] 2024-08-27 08:29
@protesilaos Any updates?

**Comment by protesilaos** [comment] 2024-08-28 08:39
> From: Valentino ***@***.***>
> Date: Tue, 27 Aug 2024 01:29:35 -0700
>
> @protesilaos Any updates?

Are you using the PGTK build of Emacs? I remember having this issue
there. Basically, it would ignore the explicitly defined frame title and
just use the current buffer name.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by luftmensch-luftmensch** [comment] 2024-08-28 08:40
It happens also on the GTK3 version (on xorg). It does not update, but it remains always stuck on the first name (*scratch*)

**Comment by protesilaos** [comment] 2024-08-28 09:00
> From: Valentino ***@***.***>
> Date: Wed, 28 Aug 2024 01:40:42 -0700
>
> It happens also on the GTK3 version (on xorg)

Does it still happen if you explicitly rename a frame? Use the command
'set-frame-name'.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by luftmensch-luftmensch** [comment] 2024-08-28 09:01
It changes, but it remains the same also when I open a different file. I'm experiencing the same behaviour of the last time

**Comment by luftmensch-luftmensch** [comment] 2024-08-30 10:25
@protesilaos Digging a bit through the commits it appears that the problem was introduced by 
the change to `beframe-infer-frame-name` in https://github.com/protesilaos/beframe/commit/af8ef1014912f6c2b3569ac22eba81a7fa62462f. Reverting the change on the latest commit restores the strange behaviour

**Comment by protesilaos** [comment] 2024-08-31 10:09
> From: Valentino ***@***.***>
> Date: Fri, 30 Aug 2024 03:25:28 -0700
>
> @protesilaos Digging a bit through the commits it appears that the
> problem was introduced by the change to `beframe-infer-frame-name` in
> https://github.com/protesilaos/beframe/commit/af8ef1014912f6c2b3569ac22eba81a7fa62462f.
> Reverting the change on the latest commit restores the strange
> behaviour

Okay, this is good to know! Now we need to understand how
'beframe-infer-frame-name' fails in your case. I suspect it has to do
with the 'projectp' part, which was returning nil before and thus
preventing the entire function from returning a value.

Can you go to a frame that would otherwise exhibit the problem and
evaluate the following? Do 'M-x eval-expression', paste it at the
minibuffer prompt, and hit RET:

    (let* ((buffer (car (frame-parameter nil 'buffer-list)))
           (dir (with-current-buffer buffer (or (vc-root-dir) default-directory)))
           (projectp (and (bound-and-true-p project--list)
                          (listp project--list)
                          (or
                           (member (list dir) project--list)
                           (member (list (abbreviate-file-name dir)) project--list)))))
      projectp)

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by luftmensch-luftmensch** [comment] 2024-08-31 10:12
I got `nil` as result doing this

**Comment by protesilaos** [comment] 2024-08-31 10:31
> From: Valentino ***@***.***>
> Date: Sat, 31 Aug 2024 03:13:09 -0700
>
> I got `nil` as result doing this

Okay, then let us handle the scenario when 'nil' is the return value.

Can you apply this diff and then check what happens?


 beframe.el | 15 +++++++++++++--
 1 file changed, 13 insertions(+), 2 deletions(-)

diff --git a/beframe.el b/beframe.el
index 22cf781..b7566ba 100644
--- a/beframe.el
+++ b/beframe.el
@@ -623,11 +623,21 @@ (defvar beframe--rename-frame-history nil
 ;;     (with-current-buffer buf
 ;;       (rename-buffer (format "*scratch for %s*" name)))))
 
+(defvar beframe-frame-name-history nil
+  "Minibuffer history of `beframe-name-prompt'.")
+
+(defun beframe-name-prompt ()
+  "Prompt for a frame name.
+See `beframe-infer-frame-name' for how this is used"
+  (read-string "Cannot infer name; how to call this frame? " nil 'beframe-frame-name-history))
+
 (defvar project--list) ; from project.el
 
 (defun beframe-infer-frame-name (frame name)
   "Infer a suitable name for FRAME with given NAME.
-See `beframe-rename-frame'."
+If a name cannot be inferred, prompt for one.
+
+See `beframe-rename-frame' for the relevant command."
   (when (frame-list)
     (let* ((buffer (car (frame-parameter frame 'buffer-list)))
            (file-name (when (bufferp buffer) (buffer-file-name buffer)))
@@ -647,8 +657,9 @@ (defun beframe-infer-frame-name (frame name)
         (format "%s %s" buf-name dir))
        ((not (minibufferp))
         buf-name)
+       (dir)
        (t
-        dir)))))
+        (beframe-name-prompt))))))
 
 ;;;###autoload
 (defun beframe-rename-frame (frame &optional name)


-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by luftmensch-luftmensch** [comment] 2024-08-31 10:41
Applying this does not fix the problem unfortunately

**Comment by luftmensch-luftmensch** [comment] 2025-02-09 20:59
Any updates on this situation?

**Comment by protesilaos** [comment] 2025-02-12 06:38
> From: Valentino ***@***.***>
> Date: Sun,  9 Feb 2025 12:59:45 -0800
>
> Any updates on this situation?

I don't know. We made some changes to 'beframe-infer-frame-name' but I
do not use the daemon (I use server-mode instead).

-- 
Protesilaos Stavrou
https://protesilaos.com
